import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { LAUNCHPAD_ADDRESS } from '../config';
import LaunchpadAbi from "../abi/launchpad.json";
import { parseEther } from 'viem';
import { waitForTransactionReceipt } from 'wagmi/actions';
import { useConfig, useWriteContract } from 'wagmi';

const Home: NextPage = () => {
  const config = useConfig();
  const { writeContractAsync } = useWriteContract();
  const createCoin = async () => {
    let tokenAddress;
    
    try {
      const url = "https://beige-personal-nightingale-17.mypinata.cloud/ipfs/QmX6gzzqnazKvVUQptswKU6c43FFdM7iAL3LLr7JtpjGuv";
      const tokenConfig = {
        name: "abc",
        symbol: "abc",
        initialSupply: 1_000_000_000_000_000_000_000_000_000n,
      };
      const metadataConfig = {
        ipfsHash: url,
        website: "",
        twitter: "",
        telegram: "",
        description: "",
        metadata: "",
      };
      const snipeConfig = {
        minAmountOut: parseEther("0.01"),
      };
      const curveParameters = {
        yMin: 51136363636n,
        yMax: 56250000000n,
      };

      const hash = await writeContractAsync({
        address: LAUNCHPAD_ADDRESS,
        abi: LaunchpadAbi,
        functionName: "createLaunchpadToken",
        args: [tokenConfig, metadataConfig, snipeConfig, curveParameters],
        value: parseEther("0.01"),
      });
      const receipt = await waitForTransactionReceipt(config, { hash });
      for (const log of receipt.logs) {
        if (
          log.topics[0] ===
          "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"
        ) {
          tokenAddress = log.address;
          console.log(tokenAddress);
          // toast.success("Coin created successfully!", { toastId });
          // navigate(`/trade/${tokenAddress}`);
          break;
        }
      }
    } catch (error: any) {
      console.log(error);
      
    } finally {
    }
  }

  const buy = async () => {
    
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <button onClick={createCoin}>Create Coin</button>
      </main>
    </div>
  );
};

export default Home;
